apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  destination:
    namespace: sample-app
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/arutselvan15/my-k8s.git
    targetRevision: develop
    path: "apps/sample-app"
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true